
import java.awt.Desktop;
import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class ExcelExporter {

    private static final String OUTPUT_DIR = "lab_exports";

    // ── Export a freshly-generated patient result ─────────────
    public static void exportAndOpen(ClinicalLabPatient patient) throws IOException {
        File file = makeFile(
            patient.getName().replaceAll("[^a-zA-Z0-9 ]", "")
                             .trim().replace(" ", "_")
        );

        try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
            writeCompanyHeader(pw);
            writePatientBlock(pw, patient);
            writeTestBlock(pw, patient);
            writeFooter(pw);
        }

        openFile(file);
    }

    // ── Export a record from the saved history by row index ───
    public static void exportFromHistory(int recordIndex) throws IOException {
        List<String[]> all = PatientRecord.loadAll();
        if (recordIndex < 0 || recordIndex >= all.size()) {
            throw new IOException("Invalid record index.");
        }

        String[] c = all.get(recordIndex);
        File file  = makeFile("HistoryRecord");

        try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
            writeCompanyHeader(pw);
            pw.println("PATIENT INFORMATION");
            pw.println("Name,"      + esc(get(c, 0)));
            pw.println("Age,"       + esc(get(c, 1)));
            pw.println("Sex,"       + esc(get(c, 2)));
            pw.println("Last Meal," + esc(get(c, 3)));
            pw.println("Date,"      + esc(get(c, 4)));
            pw.println("Time,"      + esc(get(c, 5)));
            pw.println();
            pw.println("TEST RESULTS");
            pw.println("Test Name,Result,Unit,Reference Range,Interpretation");

            if (c.length > 6 && !c[6].trim().isEmpty()) {
                for (String entry : c[6].split(";;")) {
                    String[] p = entry.split("~", -1);
                    if (p.length >= 5) {
                        pw.printf("%s,%s,%s,%s,%s%n",
                            esc(p[0]), esc(p[1]), esc(p[2]), esc(p[3]), esc(p[4]));
                    }
                }
            }
            writeFooter(pw);
        }

        openFile(file);
    }

    // ── Private helpers ───────────────────────────────────────
    private static File makeFile(String base) throws IOException {
        File dir = new File(OUTPUT_DIR);
        if (!dir.exists()) dir.mkdirs();
        String ts = LocalDateTime.now()
                .format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        return new File(dir, base + "_" + ts + ".csv");
    }

    private static void openFile(File file) throws IOException {
        if (Desktop.isDesktopSupported()
                && Desktop.getDesktop().isSupported(Desktop.Action.OPEN)) {
            Desktop.getDesktop().open(file);
        } else {
            throw new IOException(
                "File saved, but could not open automatically.\n" +
                "Location: " + file.getAbsolutePath());
        }
    }

    private static void writeCompanyHeader(PrintWriter pw) {
        pw.println("NUCOMP DIAGNOSTIC CORPORATION");
        pw.println("Clinical Chemistry Laboratory Report");
        pw.println();
    }

    private static void writePatientBlock(PrintWriter pw, ClinicalLabPatient p) {
        pw.println("PATIENT INFORMATION");
        pw.println("Name,"       + esc(p.getName()));
        pw.println("Age,"        + p.getAge());
        pw.println("Sex,"        + p.getSex());
        pw.println("Last Meal,"  + esc(p.getTimeLastMeal()));
        pw.println("Date,"       + p.getCollectionDate());
        pw.println("Time,"       + p.getCollectionTime());
        pw.println();
    }

    private static void writeTestBlock(PrintWriter pw, ClinicalLabPatient p) {
        pw.println("TEST RESULTS");
        pw.println("Test Name,Result,Unit,Reference Range,Interpretation");
        for (ClinicalLabTest t : p.getCompletedTests()) {
            pw.printf("%s,%s,%s,%s,%s%n",
                esc(t.getTestName()),
                esc(t.getFormattedResult()),
                esc(t.getUnit()),
                esc(t.getReferenceRange(p.getSex())),
                esc(t.getInterpretation(p.getSex())));
        }
        pw.println();
    }

    private static void writeFooter(PrintWriter pw) {
        pw.println("This result is for laboratory purposes only.");
        pw.println("Generated by NUCOMP Clinical Lab System");
    }

    private static String get(String[] arr, int i) {
        return (arr != null && i < arr.length) ? arr[i] : "";
    }

    // Wrap value in quotes if it contains commas or quotes
    private static String esc(String v) {
        if (v == null) return "";
        if (v.contains(",") || v.contains("\"") || v.contains("\n")) {
            return "\"" + v.replace("\"", "\"\"") + "\"";
        }
        return v;
    }
}
